### ISSUE TITLE
Move repository 

### ISSUE THREAD

**Issue by sonnyp** [GSConnect/gsconnect-ci#1]
Follow up https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1069#issuecomment-808803582

Could you please move this repository to the `GSConnect` org?

Thanks

**Comment by andyholmes** [comment]
Repository should be moved now. It doesn't seem like the Github redirect from `andyholmes/gsconnect-ci` to `GSConnect/gsconnect-ci` will work for Dockerhub, so I guess it's time to open a "GSConnect" dockerhub account.

You'll also want to make new branch here for `3.38` and then bump the image to `fedora:34` in the `master` branch so tests are run against GNOME 40.

**Comment by sonnyp** [comment]
Many thanks.

I don't have rights on this repository - can you make me owner of GSConnect org ?

It will also be required for setting up Dockerhub integration and probably other administrative / maintenance tasks

**Comment by sonnyp** [comment]
@daniellandau was kind enough to take care of this
