### ISSUE TITLE
Rename 'master' branch in CI repo

### ISSUE THREAD

**Issue by ferdnyc** [GSConnect/gsconnect-ci#7]
The default branch name `master` has fallen out of favor, for valid reasons, and GitHub [has made it as easy as possible](https://github.com/github/renaming/) to adopt the new preferred name, `main`. Renaming the branch in the existing repos will turn the old name into an API and web redirect, so all of the automation and etc. that still uses the old name should continue to work normally. That stuff is actually best updated _after_ the rename.

**Comment by andyholmes** [comment]
Seems like a good idea and has my thumbs up. Let me know if you need extra permissions to make the change!

**Comment by ferdnyc** [comment]
Nope, it _appears_ I have that power in both repos. (In fact, I'm a bit disconcerted, almost, after finding _this_ table in The Other Repo™:)

![image](https://user-images.githubusercontent.com/538020/169718871-1eab8229-d447-4235-b8c5-042372c9b33c.png)

I assume "Mixed roles" is representative of your & Sonny's admin status in the _Organization_, which trumps the repo, and therefore means that I couldn't _**really**_ stage a repo coup by virtue of being (ostensibly) the sole admin. Still, if I were the type to go power-mad, rather than being completely intimidated by it, that might be cause for concern. :roll_eyes: 

Anyway, assuming @sonnyp (or anyone else) doesn't have any objections, it appears I'm all good to do it to it. But I'll hold off a day or two, give people a chance to weigh in.

**Comment by sonnyp** [comment]
Go for it 👍

**Comment by ferdnyc** [comment]
Rename done here, please run the following commands in your local check-out:

```sh
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
